import {WEAPONS} from './content.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const combatMethods={
beginFight(n){const p=this.data.player,e=n.enemy;this.combat={npc:n,timer:90,combo:0,comboTime:0,reward:e.reward||80,assistUsed:{},winner:null,resultDelay:0,player:{name:'Shi-An',x:340,y:454,dir:1,variant:'atlas',hp:p.hp,maxHp:p.maxHp,chi:p.chi,maxChi:p.maxChi,power:p.power,defence:p.defence,weapon:WEAPONS.find(w=>w.id===p.weapon)?.kind||'staff',action:'idle',actionTime:0,hit:false,block:false},enemy:{...e,x:620,y:454,dir:-1,hp:e.maxHp,chi:40,maxChi:40,defence:Math.max(2,e.level),action:'idle',actionTime:0,hit:false,block:false}};this.mode='combat';this.sound.setMusic('battle')},
 combatPress(k){const p=this.combat?.player;if(!p||this.combat.winner)return;if(k==='KeyJ')this.attack(p,'punch');if(k==='KeyK')this.attack(p,'kick');if(k==='KeyL')this.attack(p,p.weapon==='sword'?'sword':'staff');if(k==='KeyI'&&p.chi>=30){p.chi-=30;this.attack(p,'chi')}if(k==='KeyW'&&['idle','walk'].includes(p.action)){p.action='jump';p.actionTime=0}if(/^Digit[1-4]$/.test(k))this.assist(+k.slice(-1)-1)},
 attack(f,a){if(!['idle','walk','block'].includes(f.action))return;f.action=a;f.actionTime=0;f.hit=false;f.block=false;this.sound.sfx(a==='chi'?'chi':a)},
 assist(i){const b=this.combat,a=this.data.party[i];if(!a||b.assistUsed[i])return;b.assistUsed[i]=1;b.enemy.hp-=18+i*3;this.burst(b.enemy.x,b.enemy.y-110,'#72ef92',14);this.say(`${a.name.split(' “')[0]} assists!`);this.sound.sfx('hit')},
 updateCombat(dt){const b=this.combat;if(!b)return;b.timer-=dt;b.comboTime-=dt;if(b.comboTime<=0)b.combo=0;const p=b.player,e=b.enemy;p.dir=p.x<e.x?1:-1;e.dir=e.x<p.x?1:-1;if(!b.winner){let mv=0;if(this.keys.KeyA||this.keys.ArrowLeft)mv--;if(this.keys.KeyD||this.keys.ArrowRight)mv++;if(mv&&['idle','walk'].includes(p.action)){p.x=clamp(p.x+mv*190*dt,80,880);p.action='walk'}else if(p.action==='walk')p.action='idle';p.block=!!this.keys.KeyS&&['idle','walk','block'].includes(p.action);if(p.block)p.action='block';else if(p.action==='block')p.action='idle';this.ai(dt);this.tickFighter(p,e,dt,true);this.tickFighter(e,p,dt,false);if(b.timer<=0||p.hp<=0||e.hp<=0){b.winner=e.hp<=0||p.hp>e.hp?'player':'enemy';b.resultDelay=.8}}else if((b.resultDelay-=dt)<=0)this.mode=b.winner==='player'?'victory':'defeat'},
 ai(dt){const b=this.combat,e=b.enemy,p=b.player;if(!['idle','walk','block'].includes(e.action))return;const d=Math.abs(e.x-p.x);if(Math.random()<dt*(d<150?1.7:.5)){if(d>150)e.x+=Math.sign(p.x-e.x)*95;else if(Math.random()<.25){e.block=true;e.action='block'}else this.attack(e,Math.random()<.25&&e.weapon?e.weapon:Math.random()<.5?'punch':'kick')}else if(d>120)e.x+=Math.sign(p.x-e.x)*55*dt},
 tickFighter(f,o,dt,isPlayer){if(['idle','walk','block'].includes(f.action))return;f.actionTime+=dt;const specs={punch:[.14,.34,62,13],kick:[.2,.48,86,19],sword:[.2,.5,112,23],staff:[.22,.52,126,21],chi:[.25,.62,150,32],jump:[99,.65,0,0],hurt:[99,.3,0,0]};const [hitAt,dur,range,base]=specs[f.action]||specs.punch;if(!f.hit&&f.actionTime>=hitAt){f.hit=true;if(range&&Math.abs(f.x-o.x)<range)this.hit(o,Math.max(1,base+f.power-(o.defence||0)),isPlayer)}if(f.actionTime>=dur){f.action='idle';f.actionTime=0;f.hit=false}},
 hit(target,damage,byPlayer){if(target.block){damage=Math.ceil(damage*.25);this.sound.sfx('block')}else this.sound.sfx('hit');target.hp=Math.max(0,target.hp-damage);target.action='hurt';target.actionTime=0;target.hit=false;this.shake=8;this.burst(target.x,target.y-100,target.block?'#e5d179':'#ef694e',10);if(byPlayer){this.combat.combo++;this.combat.comboTime=1.1;this.combat.player.chi=Math.min(this.combat.player.maxChi,this.combat.player.chi+6)}},
 burst(x,y,color,n){for(let i=0;i<n;i++)this.particles.push({x:x+(Math.random()-.5)*25,y:y+(Math.random()-.5)*35,vx:(Math.random()-.5)*170,vy:(Math.random()-.5)*140,size:3+Math.random()*7,color,life:.3+Math.random()*.4})},
 finishResult(){const b=this.combat;if(this.mode==='defeat'){this.data.player.hp=this.data.player.maxHp;this.data.player.chi=this.data.player.maxChi;this.mode='explore';this.combat=null;this.sound.setMusic(this.location().music==='mountain-theme'?'mountain':'village');return}const id=b.npc.id;this.data.player.hp=Math.max(1,b.player.hp);this.data.player.chi=b.player.chi;this.data.player.silver+=b.reward;this.data.defeated.push(id);if(id==='kuo'){this.setQuest('ambush','completed');this.setQuest('silent-bell','active')}if(id==='novice-jin'){this.setQuest('silent-bell','completed');this.setQuest('five-shadows','active');this.data.player.style='Shaolin Long Fist'}if(id==='ghost-face'){this.setQuest('faceless','completed');this.mode='act-complete'}else this.mode='explore';this.combat=null;this.save();this.sound.sfx('victory');this.sound.setMusic(this.location().music==='mountain-theme'?'mountain':'village')}
};
