import {WEAPONS} from './content.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const ready=f=>['idle','walk','block'].includes(f.action);
const art=(id,fallback)=>globalThis.greenDragonAssets?.sprites?.[id]?id:fallback;
const ATTACKS={punch:{cost:10,hitAt:.14,duration:.34,range:62,damage:13},kick:{cost:16,hitAt:.2,duration:.48,range:86,damage:19},sword:{cost:18,hitAt:.2,duration:.5,range:112,damage:23},staff:{cost:20,hitAt:.22,duration:.52,range:126,damage:21},chi:{cost:0,hitAt:.25,duration:.62,range:150,damage:32}};

export const combatMethods={
 beginFight(n){
  const p=this.data.player,e=n.enemy;
  this.combat={npc:n,timer:90,combo:0,comboTime:0,reward:e.reward||80,assistUsed:{},winner:null,resultDelay:0,
   player:{name:'Shi-An',sprite:art('shi-an',null),x:340,y:454,dir:1,variant:'atlas',hp:p.hp,maxHp:p.maxHp,chi:p.chi,maxChi:p.maxChi,power:p.power,defence:p.defence,weapon:WEAPONS.find(w=>w.id===p.weapon)?.kind||'staff',action:'idle',actionTime:0,hit:false,block:false,stamina:100,maxStamina:100,guard:100,maxGuard:100,invulnerable:0,evadeCooldown:0},
   enemy:{...e,sprite:art(n.id,null),x:620,y:454,dir:-1,hp:e.maxHp,chi:40,maxChi:40,defence:Math.max(2,e.level),action:'idle',actionTime:0,hit:false,block:false,stamina:100,maxStamina:100,guard:100,maxGuard:100,invulnerable:0,evadeCooldown:0}};
  this.mode='combat';this.sound.setMusic('battle');
 },
 combatPress(k){const b=this.combat,p=b?.player;if(!p||b.winner)return;if(k==='KeyJ')this.attack(p,'punch');if(k==='KeyK')this.attack(p,'kick');if(k==='KeyL')this.attack(p,p.weapon==='sword'?'sword':'staff');if(k==='KeyI'&&p.chi>=30){p.chi-=30;this.attack(p,'chi')}if(k==='KeyW'&&ready(p)){p.action='jump';p.actionTime=0;p.block=false}if(k==='Space')this.evade(p);if(k==='KeyU')this.throwFighter(p,b.enemy,true);if(/^Digit[1-4]$/.test(k))this.assist(+k.slice(-1)-1)},
 attack(f,a){const spec=ATTACKS[a];if(!spec||!ready(f)||f.stamina<spec.cost)return false;f.stamina-=spec.cost;f.action=a;f.actionTime=0;f.hit=false;f.block=false;this.sound.sfx(a==='chi'?'chi':a);return true},
 evade(f){if(!ready(f)||f.evadeCooldown>0||f.stamina<22)return false;f.stamina-=22;f.evadeCooldown=.55;f.invulnerable=.3;f.block=false;f.action='crouch';f.actionTime=0;f.x=clamp(f.x-f.dir*62,70,890);this.sound.sfx('move');this.burst(f.x,f.y-20,'#b8d8c0',6);return true},
 throwFighter(attacker,target,byPlayer){if(!ready(attacker)||attacker.stamina<30||Math.abs(attacker.x-target.x)>76||target.invulnerable>0)return false;attacker.stamina-=30;attacker.action='punch';attacker.actionTime=.05;attacker.hit=true;attacker.block=false;const damage=Math.max(8,15+attacker.power-Math.floor((target.defence||0)*.4)+(target.block?9:0));target.block=false;target.guard=Math.max(0,target.guard-36);target.hp=Math.max(0,target.hp-damage);target.action='hurt';target.actionTime=0;target.hit=false;target.x=clamp(target.x+attacker.dir*76,70,890);this.shake=10;this.burst(target.x,target.y-95,'#f0c96c',14);this.sound.sfx('hit');if(byPlayer){this.combat.combo++;this.combat.comboTime=1.2;attacker.chi=Math.min(attacker.maxChi,attacker.chi+9)}return true},
 assist(i){const b=this.combat,a=this.data.party[i];if(!a||b.assistUsed[i]||b.winner)return;b.assistUsed[i]=1;b.enemy.hp=Math.max(0,b.enemy.hp-(18+i*3));b.enemy.guard=Math.max(0,b.enemy.guard-20);this.burst(b.enemy.x,b.enemy.y-110,'#72ef92',14);this.say(`${a.name.split(' “')[0]} assists!`);this.sound.sfx('hit')},
 updateCombat(dt){const b=this.combat;if(!b)return;b.timer-=dt;b.comboTime-=dt;if(b.comboTime<=0)b.combo=0;const p=b.player,e=b.enemy;for(const f of [p,e]){f.stamina=Math.min(f.maxStamina,f.stamina+24*dt);f.guard=Math.min(f.maxGuard,f.guard+9*dt);f.invulnerable=Math.max(0,f.invulnerable-dt);f.evadeCooldown=Math.max(0,f.evadeCooldown-dt)}p.dir=p.x<e.x?1:-1;e.dir=e.x<p.x?1:-1;if(!b.winner){let mv=0;if(this.keys.KeyA||this.keys.ArrowLeft)mv--;if(this.keys.KeyD||this.keys.ArrowRight)mv++;if(mv&&ready(p)&&p.stamina>0){p.x=clamp(p.x+mv*190*dt,80,880);p.action='walk';p.stamina=Math.max(0,p.stamina-4*dt)}else if(p.action==='walk')p.action='idle';p.block=!!this.keys.KeyS&&ready(p)&&p.guard>0;if(p.block)p.action='block';else if(p.action==='block')p.action='idle';this.ai(dt);this.tickFighter(p,e,dt,true);this.tickFighter(e,p,dt,false);if(b.timer<=0||p.hp<=0||e.hp<=0){b.winner=e.hp<=0||p.hp>e.hp?'player':'enemy';b.resultDelay=.8}}else if((b.resultDelay-=dt)<=0)this.mode=b.winner==='player'?'victory':'defeat'},
 ai(dt){const b=this.combat,e=b.enemy,p=b.player;if(!ready(e))return;const d=Math.abs(e.x-p.x);if(p.action&&!ready(p)&&Math.random()<dt*.7&&d<125&&e.evadeCooldown<=0){this.evade(e);return}if(Math.random()<dt*(d<150?1.8:.55)){if(d>150)e.x+=Math.sign(p.x-e.x)*95;else if(p.block&&Math.random()<.45)this.throwFighter(e,p,false);else if(Math.random()<.23&&e.guard>20){e.block=true;e.action='block'}else this.attack(e,Math.random()<.28&&e.weapon?e.weapon:Math.random()<.52?'punch':'kick')}else if(d>120)e.x+=Math.sign(p.x-e.x)*55*dt},
 tickFighter(f,o,dt,isPlayer){if(ready(f))return;f.actionTime+=dt;if(f.action==='crouch'){if(f.actionTime>=.3){f.action='idle';f.actionTime=0}return}const spec=ATTACKS[f.action]||({hitAt:99,duration:f.action==='jump'?.65:.3,range:0,damage:0});if(!f.hit&&f.actionTime>=spec.hitAt){f.hit=true;if(spec.range&&Math.abs(f.x-o.x)<spec.range)this.hit(o,Math.max(1,spec.damage+f.power-(o.defence||0)),isPlayer)}if(f.actionTime>=spec.duration){f.action='idle';f.actionTime=0;f.hit=false}},
 hit(target,damage,byPlayer){if(target.invulnerable>0){this.burst(target.x,target.y-90,'#d5eee0',5);return}let blocked=false;if(target.block&&target.guard>0){blocked=true;target.guard=Math.max(0,target.guard-damage*2.1);damage=Math.ceil(damage*.25);this.sound.sfx('block');if(target.guard<=0){blocked=false;damage=Math.max(damage,10);target.block=false;this.say('Guard broken!')}}else this.sound.sfx('hit');target.hp=Math.max(0,target.hp-damage);target.action='hurt';target.actionTime=0;target.hit=false;this.shake=blocked?4:8;this.burst(target.x,target.y-100,blocked?'#e5d179':'#ef694e',blocked?7:10);if(byPlayer){this.combat.combo++;this.combat.comboTime=1.1;this.combat.player.chi=Math.min(this.combat.player.maxChi,this.combat.player.chi+(blocked?3:6))}},
 burst(x,y,color,n){for(let i=0;i<n;i++)this.particles.push({x:x+(Math.random()-.5)*25,y:y+(Math.random()-.5)*35,vx:(Math.random()-.5)*170,vy:(Math.random()-.5)*140,size:3+Math.random()*7,color,life:.3+Math.random()*.4})},
 finishResult(){const b=this.combat;if(this.mode==='defeat'){this.data.player.hp=this.data.player.maxHp;this.data.player.chi=this.data.player.maxChi;this.mode='explore';this.combat=null;this.sound.setMusic(this.location().music==='mountain-theme'?'mountain':'village');return}const id=b.npc.id;this.data.player.hp=Math.max(1,b.player.hp);this.data.player.chi=b.player.chi;this.data.player.silver+=b.reward;this.data.defeated.push(id);if(id==='kuo'){this.setQuest('ambush','completed');this.setQuest('silent-bell','active')}if(id==='novice-jin'){this.setQuest('silent-bell','completed');this.setQuest('five-shadows','active');this.data.player.style='Shaolin Long Fist'}if(id==='ghost-face'){this.setQuest('faceless','completed');this.mode='act-complete'}else this.mode='explore';this.combat=null;this.save();this.sound.sfx('victory');this.sound.setMusic(this.location().music==='mountain-theme'?'mountain':'village')}
};