import {LOCATIONS,NPCS,QUESTS,ITEMS,WEAPONS} from './content.js';
import {Sound} from './audio.js';
import {render} from './render.js';
import {combatMethods} from './combat.js';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d',{alpha:false}),loading=document.getElementById('loading');ctx.imageSmoothingEnabled=false;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const fresh=()=>({version:2,playSeconds:0,location:'jade-river',player:{x:445,y:454,level:1,exp:0,hp:120,maxHp:120,chi:70,maxChi:70,silver:120,weapon:'training-staff',style:'Green Dragon Fist',power:8,defence:4,speed:7},inventory:{'herbal-tonic':2,'rice-bowl':1},party:[],quests:Object.fromEntries(QUESTS.map((q,i)=>[q.id,i?'locked':'available'])),flags:{},defeated:[]});
const mem={};const store={get:k=>{try{return localStorage.getItem(k)}catch{return mem[k]||null}},set:(k,v)=>{try{localStorage.setItem(k,v)}catch{mem[k]=v}}};
export class Game{
 constructor(){this.ctx=ctx;this.sound=new Sound;this.data=fresh();this.hasSave=!!store.get('greenDragonSave');this.mode='title';this.time=0;this.last=performance.now();this.keys={};this.titleIndex=0;this.facing=1;this.walking=false;this.locationFlash=2;this.dialogue=null;this.menu={tab:0,index:0};this.shop={index:0};this.train={index:0};this.combat=null;this.particles=[];this.toast='';this.toastTime=0;this.shake=0;this.lessons=[['Willow Step',80,'willow','Speed +1'],['Iron Guard',100,'iron','Defence +1'],['Green Dragon Breath',130,'breath','Maximum Chi +20'],['Staff Circle',150,'staffCircle','Staff damage +3'],['Shaolin Long Fist',180,'shaolin','Power +2']];
  addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(!this.keys[e.code])this.press(e.code);this.keys[e.code]=1;this.sound.unlock()});addEventListener('keyup',e=>this.keys[e.code]=0);document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key,d=e=>{e.preventDefault();b.classList.add('active');if(!this.keys[k])this.press(k);this.keys[k]=1;this.sound.unlock()},u=e=>{e.preventDefault();b.classList.remove('active');this.keys[k]=0};b.addEventListener('pointerdown',d);['pointerup','pointercancel','pointerleave'].forEach(v=>b.addEventListener(v,u))})}
 start(){loading.style.display='none';this.sound.setMusic('village');requestAnimationFrame(t=>this.loop(t))}
 loop(now){const dt=Math.min(.034,(now-this.last)/1000);this.last=now;this.time+=dt;this.update(dt);render(this);requestAnimationFrame(t=>this.loop(t))}
 location(){return LOCATIONS.find(x=>x.id===this.data.location)||LOCATIONS[0]}
 quest(id){return this.data.quests[id]||'locked'} setQuest(id,s){this.data.quests[id]=s}
 say(msg){this.toast=msg;this.toastTime=2}
 save(){store.set('greenDragonSave',JSON.stringify(this.data));this.hasSave=true;this.say('Journey saved')}
 load(){try{const d=JSON.parse(store.get('greenDragonSave'));if(d){this.data=d;this.mode='explore';this.locationFlash=2;this.sound.setMusic(this.location().music==='mountain-theme'?'mountain':'village')}}catch{} }
 newGame(){this.data=fresh();this.mode='explore';this.locationFlash=2;this.save();this.sound.setMusic('village')}
 nearestNpc(){let best=null,d=1e9;for(const n of NPCS[this.data.location]||[]){if(this.data.defeated.includes(n.id))continue;const x=Math.abs(n.x-this.data.player.x);if(x<d){d=x;best=n}}return best}
 press(k){if(k==='KeyP'){this.sound.toggle();this.say(this.sound.on?'Sound on':'Sound off');return}if(this.mode==='title')return this.titlePress(k);if(this.mode==='dialogue')return this.dialoguePress(k);if(this.mode==='menu')return this.menuPress(k);if(this.mode==='shop')return this.shopPress(k);if(this.mode==='train')return this.trainPress(k);if(this.mode==='combat')return this.combatPress(k);if(this.mode==='victory'||this.mode==='defeat')return ['Enter','KeyE'].includes(k)&&this.finishResult();if(this.mode==='act-complete')return ['Enter','KeyE'].includes(k)&&(this.mode='explore');if(['KeyM','Escape'].includes(k)){this.mode='menu';this.menu={tab:0,index:0};return}if(k==='KeyE'||k==='Enter')this.interact();if(k==='KeyQ')this.useItem('herbal-tonic')}
 titlePress(k){const options=this.hasSave?['continue','new','chronicle','sound']:['new','chronicle','sound'];if(['ArrowUp','KeyW'].includes(k)){this.titleIndex=(this.titleIndex+options.length-1)%options.length;this.sound.sfx('move')}if(['ArrowDown','KeyS'].includes(k)){this.titleIndex=(this.titleIndex+1)%options.length;this.sound.sfx('move')}if(['Enter','KeyE'].includes(k)){const o=options[this.titleIndex];this.sound.sfx('ok');if(o==='continue')this.load();if(o==='new')this.newGame();if(o==='chronicle'){this.newGame();this.mode='menu';this.menu={tab:4,index:0}}if(o==='sound')this.sound.toggle()}}
 update(dt){if(this.mode!=='title')this.data.playSeconds+=dt;this.locationFlash=Math.max(0,this.locationFlash-dt);this.toastTime=Math.max(0,this.toastTime-dt);this.shake=Math.max(0,this.shake-dt*24);this.particles=this.particles.filter(p=>(p.life-=dt)>0).map(p=>(p.x+=p.vx*dt,p.y+=p.vy*dt,p));if(this.mode==='explore')this.updateExplore(dt);if(this.mode==='dialogue')this.dialogue.reveal+=dt*48;if(this.mode==='combat')this.updateCombat(dt)}
 updateExplore(dt){let d=0;if(this.keys.KeyA||this.keys.ArrowLeft)d--;if(this.keys.KeyD||this.keys.ArrowRight)d++;this.walking=!!d;if(d){this.facing=d;this.data.player.x+=d*(145+this.data.player.speed*4)*dt}if(this.data.player.x<10)this.travel(-1);if(this.data.player.x>950)this.travel(1)}
 travel(dir){const i=LOCATIONS.findIndex(x=>x.id===this.data.location),n=clamp(i+dir,0,LOCATIONS.length-1);if(n===i){this.data.player.x=dir<0?20:940;this.say('The road beyond is not open yet.');return}this.data.location=LOCATIONS[n].id;this.data.player.x=dir>0?40:920;this.locationFlash=2;this.sound.setMusic(this.location().music==='mountain-theme'?'mountain':'village');this.save()}
 interact(){const n=this.nearestNpc();if(!n||Math.abs(n.x-this.data.player.x)>92)return this.say('No one is close enough to speak with.');this.dialogue={npc:n,lines:n.lines,index:0,reveal:0};this.mode='dialogue';this.sound.sfx('ok')}
 dialoguePress(k){if(!['Enter','KeyE','Space'].includes(k))return;const d=this.dialogue,line=d.lines[d.index];if(d.reveal<line.length){d.reveal=999;return}if(++d.index<d.lines.length){d.reveal=0;this.sound.sfx('move');return}const n=d.npc;this.mode='explore';this.dialogue=null;this.afterTalk(n)}
 afterTalk(n){const id=n.id;if(id==='elder-zhao'){this.setQuest('ashes','completed');this.setQuest('footprints','active');this.data.player.silver+=60}if(id==='hunter-fong'){this.setQuest('footprints','completed');this.setQuest('teahouse','active');this.data.player.silver+=90}if(id==='tea-lian'){this.setQuest('teahouse','completed');this.setQuest('ambush','active');this.data.player.silver+=120}if(id==='mei-lin')this.recruit(n,'White Crane Wing');if(id==='bo')this.recruit(n,'Iron Ox Body');if(['merchant-han','broker-qiu'].includes(id)){this.shop={index:0};this.mode='shop'}if(['hermit-reed','abbot-wu'].includes(id)){this.train={index:0};this.mode='train'}if(id==='abbot-wu'&&this.quest('ambush')==='completed')this.setQuest('silent-bell','active');if(n.enemy)this.beginFight(n);if(id==='white-brow'){this.setQuest('faceless','active');this.say('The executioner waits at the far end of the walkway.')}}
 recruit(n,style){if(this.data.party.some(x=>x.id===n.id))return this.say(`${n.name.split(' “')[0]} already travels with you.`);if(this.data.party.length>=5)return this.say('Your five companion places are full.');this.data.party.push({id:n.id,name:n.name,variant:n.variant,style});this.say(`${n.name.split(' “')[0]} joined the party.`);if(this.data.party.length>=2)this.setQuest('five-shadows','completed');this.save()}
 useItem(id){if(!(this.data.inventory[id]>0))return this.say('You do not have that item.');const p=this.data.player,it=ITEMS.find(x=>x.id===id);if(it.effect.startsWith('heal'))p.hp=Math.min(p.maxHp,p.hp+(it.effect==='heal'?35:18));if(it.effect==='chi')p.chi=Math.min(p.maxChi,p.chi+30);this.data.inventory[id]--;this.say(`${it.name} used.`)}
 menuPress(k){if(k==='Escape'||k==='KeyM'){this.mode='explore';return}if(k==='KeyQ'){this.menu.tab=(this.menu.tab+5)%6;this.menu.index=0}if(k==='KeyE'){this.menu.tab=(this.menu.tab+1)%6;this.menu.index=0}if(['ArrowUp','KeyW'].includes(k))this.menu.index=Math.max(0,this.menu.index-1);if(['ArrowDown','KeyS'].includes(k))this.menu.index++;if(k==='Enter'&&this.menu.tab===0){const ids=Object.keys(this.data.inventory).filter(x=>this.data.inventory[x]>0);if(ids.length)this.useItem(ids[this.menu.index%ids.length])}}
 shopPress(k){const stock=[...ITEMS,...WEAPONS.slice(0,5)];if(k==='Escape'){this.mode='explore';return}if(['ArrowUp','KeyW'].includes(k))this.shop.index=(this.shop.index+stock.length-1)%stock.length;if(['ArrowDown','KeyS'].includes(k))this.shop.index=(this.shop.index+1)%stock.length;if(k==='Enter'||k==='KeyE'){const it=stock[this.shop.index];if(this.data.player.silver<it.price)return this.say('Not enough silver.');this.data.player.silver-=it.price;if('kind'in it){this.data.player.weapon=it.id;this.say(`${it.name} equipped.`)}else{this.data.inventory[it.id]=(this.data.inventory[it.id]||0)+1;this.say(`${it.name} purchased.`)}this.sound.sfx('ok')}}
 trainPress(k){if(k==='Escape'){this.mode='explore';return}if(['ArrowUp','KeyW'].includes(k))this.train.index=(this.train.index+this.lessons.length-1)%this.lessons.length;if(['ArrowDown','KeyS'].includes(k))this.train.index=(this.train.index+1)%this.lessons.length;if(k==='Enter'||k==='KeyE'){const [name,cost,flag]=this.lessons[this.train.index],p=this.data.player;if(this.data.flags[flag])return this.say('You already mastered this lesson.');if(p.silver<cost)return this.say('You need more silver for this training.');p.silver-=cost;this.data.flags[flag]=1;if(flag==='willow')p.speed++;if(flag==='iron')p.defence++;if(flag==='breath'){p.maxChi+=20;p.chi=p.maxChi}if(flag==='staffCircle')p.power+=3;if(flag==='shaolin'){p.power+=2;p.style='Shaolin Long Fist'}this.say(`${name} mastered.`);this.save()}}
}
Object.assign(Game.prototype,combatMethods);
const game=new Game;globalThis.greenDragonGame=game;game.start();
